### PR TITLE
RESSERV-76: Apply (FLUID-4942) Fixes Infusion event system bug with Prot...

### PR DESCRIPTION
**Pull request by auxepaul**
...otype.js (fluid 1.4.X bug)

### CODE REVIEW

**Comment by jameswennmacher** [comment]
Hmmm... Should we patch the current upmc JS or create a new upmc JS version which means source code references would need to change??  It could be confusing for the community referencing the same upmc JS but having different code based on which version of the resource server you are using.  We have generally not modified resources on the resource server once they have been released.

**Comment by apetro** [comment]
I expect a name like `1.4.0-upmc/js/fluid-all-1.4.0.js` to be a static, unchanging, immutable tag.  Do a release with a bumped version number to release a new version of a thing. Or invent `1.4.x-upmc/js/fluid-all-1.4.x.js` if what we meant to represent is a moving-target 1.4-ish thing rather than a particular release tag.  But I'd rather have real releases. :smile:

**Comment by ChristianMurphy** [comment]
Fluid [1.5](https://github.com/fluid-project/infusion/releases/tag/infusion-1.5) and [2.0](https://github.com/fluid-project/infusion/releases/tag/infusion-2.0) both contain this patch.

**Comment by cousquer** [comment]
👍 
#https://github.com/Jasig/email-preview/pull/70/commits/be1b0f3d317e90e498750196985dec2a7cd40422

**Comment by bjagg** [comment]
Is this no addressed with the new versions of Fluid that were recently merged?

**Comment by ChristianMurphy** [comment]
Thanks for the pull request @auxepaul!
This has been addressed when newer versions of fluid were merged into resource server in #47 and #48.
Using a new official release rather than modifying a previous release seems like the way to go (see https://github.com/Jasig/resource-server/pull/35#issuecomment-71706952 and https://github.com/Jasig/resource-server/pull/35#issuecomment-71712441).

**Pull request closed without merging**
