### PR TITLE
RESSERV-93: Add Fluid Infusion 2.0.0

### PR DESCRIPTION
**Pull request by ChristianMurphy**
https://issues.jasig.org/browse/RESSERV-93

Version 2 is almost a complete rewrite of Fluid.
See the release post of all the details https://github.com/fluid-project/infusion/releases/tag/infusion-2.0
NOTE: the fluid skinning system has been removed

downloaded from [infusion-all-2.0.0-minified.zip](https://github.com/fluid-project/infusion/releases/tag/infusion-2.0)

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@jobara re https://github.com/Jasig/email-preview/pull/70 is the `infusion-all.js` the only file that should be needed to use the fluid components?

**Comment by cousquer** [comment]
@jobara @ChristianMurphy what's the minimal version of jQuery needed for infusion 2.0.0, and what version of JavaScript are you running in infusion 2.0.0 : ES3, ESS5, ES2015 (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript/ECMAScript_Next_support_in_Mozilla) ?

**Comment by ChristianMurphy** [comment]
@cousquer As far as I can tell, [jQuery 3.1.0](https://github.com/fluid-project/infusion/blob/master/src/lib/jquery/core/js/jquery.js#L3) and [ES5/ES2009](https://jquery.com/browser-support/) [(due to IE9 support)](https://kangax.github.io/compat-table/es6/#ie9).

**Comment by cousquer** [comment]
@jobara @ChristianMurphy  Yeah for jQuery [ok](https://jquery.com/browser-support/) 
but it's unclear for me for infusion 2.0.0, the doc is saying [IE11 only ](https://github.com/fluid-project/infusion#source-maps) , it's not a problem (ok for me for dropping IE9 :clap: :smiley:), but we just simply need to know. :smile:

**Comment by ChristianMurphy** [comment]
IE 11 has [very limited ES2015](https://kangax.github.io/compat-table/es6/#ie11) support.
I think ES5 is the target version, wi, but @jobara can confirm.

**Comment by cousquer** [comment]
just want to know for:

- [const  & let](http://www.ecma-international.org/ecma-262/6.0/#sec-let-and-const-declarations) 
- [block-level function declaration](http://www.ecma-international.org/ecma-262/6.0/#sec-functiondeclarationinstantiation)

:wink:

**Comment by amb26** [comment]
Yes, we are at ES5 for IE11, but this needn't hold you back from using modern language features elsewhere in your codebase, right? ES/JS essentially never introduces non-forward compatible language features, unless they are hidden behind "invitation" directives such as "use strict".

**Comment by jobara** [comment]
@ChristianMurphy and @cousquer, sorry I was away on vacation. We haven't explicitly pegged an ECMAScript version but will use what's available in our browser support. For 2.0 we tested with Chrome 54, Firefox 49, IE 11, MS Edge 38, and Safari 10. https://github.com/fluid-project/infusion/blob/infusion-2.0/ReleaseNotes.md#supported-browsers

Regarding `infusion-all.js`, for JS it should be all you need. If you want to use our HMTL and CSS you'll need to add those in as well. Let me know if something seems missing. You can also make custom builds if you don't want all of infusion. https://github.com/fluid-project/infusion/tree/infusion-2.0#how-do-i-create-an-infusion-package

**Comment by ChristianMurphy** [comment]
Thanks @amb26 and @jobara !

**Comment by cousquer** [comment]
@ChristianMurphy @amb26 & @jobara Many many thanks for the feedbacks. 👍 
@amb26 about "use strict" : uPortal is a little sensitive to script concatenation... I can only open the _!fu,#(!_ MS IE11's devTools by disabling uPortal's concatenation... 😸 
Maybe the safest bet is to add semicolons defensively, perhaps.

```
;(function() {
    "use strict";
    // ...
})()
```
@jobara Thanks, now I'm struggling a bit with [VoiceOver's touch areas on links](https://twitter.com/stevefaulkner/status/818404891458670592). 😄

**Comment by jobara** [comment]
@cousquer what issue are you running into with links and VoiceOver?

**Comment by cousquer** [comment]
@jobara @ChristianMurphy 
Give me a couple of hours to write quite correctly in english (btw: I'm french).
I will try to give you feedbacks tonight (Paris Time Zone). 
Mac OS X Safari keyboard navigation is definitely strange and very creative, IMHO. 😃

**Comment by cousquer** [comment]
@jobara @ChristianMurphy ,
When I read [the VoiceOver documentation](https://help.apple.com/voiceover/info/guide/10.12/#/vo27992) (web-based keyboard navigation and gestures), I humbly feel that people with disabilities are being asked to do things [like this](https://www.youtube.com/watch?v=Mflg-PzioHA) on a rectangular touch surface of 0.30 in diagonal while learning a big documentation at the same time...

However, I noticed that VoiceOver visually interacts with the bootstrap .sr-only CSSclass by framing it in black on IOS / Safari && Chrome && FF MacOsXSafari and this area never corresponds to the link with the "btn" class. The history of role = "application" and other had me put aside this.
I noticed that this framed area corresponded with the hidden text box for screen readers with the Bootstrap CSS class: "sr-only" (aka I'm reading this so the longer your label is The black frame is large and this is not the trigger area of the link.

the bug on IOS

WIP the begining of the solution are here : 

touch area =

When Voice Over is enable touch areas are allmost the same as and the focus Zone on hidden text zone.

PR in a couple of hour...

**Comment by cousquer** [comment]
@jobara @ChristianMurphy 
btw: A few weeks before Christmas, DINSIC, the Interdepartmental Directorate of Digital and Information and Communication System of France, published a [guide ](https://disic.github.io/guide-lecteurs_ecran/index.html) to help smoothly test JavaScript components using screen readers.

**Comment by jobara** [comment]
@cousquer it's good that you're getting them to line up correctly. VoiceOver users on iOS can drag their finger around the screen, as opposed to using the swipe gesture, to navigate items. This is also used for discovery of elements. [WebAIM](http://webaim.org/articles/#evaluation) also has some useful guides.

**Pull request merged**
